name: digestive-diseases-network
dependencies:
  - python>=3
  - openjdk=8.0.121
  - notebook>=5.7.6
  - tornado>6
  - ipywidgets>=7.0.0
  - nodejs
  - pandas
  - maven
  - py4j
  - requests
  - graphviz
